[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "example"
authors = [{name = "SevenTechnologies", email = "admin@seventechnologies.cloud"}]
dynamic = ["version", "description"]
